# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Redirect SPA routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
